# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "1905.1"
      
    #   config.vm.synced_folder "./", "/vagrant", enabled: "false", type: "smb"
      
    #  *config.vm.network "forwarded_port", guest: 80, host: 8080
      
     config.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
       vb.cpus = "1"
  end	 
  #   config.vm.provision "shell", inline: <<-SHELL
  #    yum update -y
  #   SHELL
  end