# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :systemd => {
        :box_name => "centos/7",
        :box_version => "1905.1",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1905.1"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "512"]
  
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd wget -y
          SHELL
        box.vm.provision "shell", path: "watcher.sh"
        box.vm.provision "shell", path: "spawn-fcgi.sh"
        box.vm.provision "shell", path: "httpd.sh"  
        end
    end
  end
