# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.255.13', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
                   {ip: '192.168.0.1', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                ]
  },
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},

                ]
  },
  :inetRouter2 => {
        :box_name => "centos/7",
        :net => [                
                   {ip: '192.168.255.14', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
                   {ip: '192.168.50.2', netmask: "255.255.255.252", adapter: 3,virtualbox__hostonly: "host" },
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip route add 192.168.0.0/16 via 192.168.255.2
            echo "192.168.0.0/16 via 192.168.255.2" >> /etc/sysconfig/network-scripts/route-eth1
            iptables-restore < /vagrant/configs/inetRouter_knock
            service iptables save
            sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo net.ipv4.conf.all.forwarding=1 >> /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            ip route del default
            ip route add default via 192.168.255.1
            ip route add 192.168.50.0/30 via 192.168.255.14
            echo "192.168.50.0/30 via 192.168.255.14" >> /etc/sysconfig/network-scripts/route-eth2
            systemctl restart network
            yum install -y nmap telnet
            SHELL
        when "inetRouter2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo net.ipv4.conf.all.forwarding=1 >> /etc/sysctl.conf
            ip route add 192.168.0.0/28 via 192.168.255.13
            echo "192.168.0.0/28 via 192.168.255.13" >> /etc/sysconfig/network-scripts/route-eth1
            systemctl restart network
            yum install -y iptables-services
            systemctl enable iptables
            iptables-restore < /vagrant/configs/inetRouter2
            service iptables save
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL           
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            ip route del default
            ip route add default via 192.168.0.1
            yum install -y epel-release
            yum install -y nginx
            systemctl start nginx
            SHELL
        end
      end

  end
  
  
end

